### ISSUE TITLE
Can't Install with php 7.2

### ISSUE THREAD

**Issue by IslamovRhino** [mygento/metrika#4]
I am trying to install module on Magento 2.3
require mygento/metrika:2.*  gives:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mygento/metrika 2.2.1 requires mygento/base ^2.2.5 -> satisfiable by mygento/base[2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9].
    - mygento/metrika 2.2.2 requires mygento/base ^2.2.5 -> satisfiable by mygento/base[2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9].
    - mygento/metrika 2.2.0 requires mygento/base 2.2.* -> satisfiable by mygento/base[2.2.0, 2.2.1, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9].
    - mygento/metrika 2.1.0 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/metrika 2.0.4 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/metrika 2.0.3 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/metrika 2.0.2 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.9 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.8 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.7 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.6 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.5 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.4 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.3 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.2 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.16 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.15 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.14 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.13 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.12 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.1 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/base 2.2.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/metrika 2.0.1 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - mygento/metrika 2.0.0 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.2.16) does not satisfy that requirement.
    - Installation request for mygento/metrika 2.* -> satisfiable by mygento/metrika[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.2.0, 2.2.1, 2.2.2].

Tried require mygento/metrika:2.* --ignore-platform-reqs, but that gives:
  Problem 1
    - Installation request for magento/framework (locked at 102.0.1) -> satisfiable by magento/framework[102.0.1].
    - Installation request for mygento/metrika 2.* -> satisfiable by mygento/metrika[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.2.0, 2.2.1, 2.2.2].
    - Can only install one of: colinmollenhour/php-redis-session-abstract[v1.4.1, v1.3.4].
    - Can only install one of: colinmollenhour/php-redis-session-abstract[v1.3.4, v1.4.1].
    - Can only install one of: colinmollenhour/php-redis-session-abstract[v1.3.4, v1.4.1].
    - Conclusion: install colinmollenhour/php-redis-session-abstract v1.3.4
    - Installation request for colinmollenhour/php-redis-session-abstract (locked at v1.4.1) -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.4.1].

and

  Problem 1
    - Installation request for colinmollenhour/php-redis-session-abstract (locked at v1.4.1) -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.4.1].
    - Conclusion: don't install colinmollenhour/php-redis-session-abstract v1.3.4
    - Installation request for mygento/metrika 2.* -> satisfiable by mygento/metrika[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.2.0, 2.2.1, 2.2.2].
    - Can only install one of: magento/framework[101.0.0, 102.0.1].
    - Can only install one of: magento/framework[102.0.1, 101.0.0].
    - Can only install one of: magento/framework[102.0.1, 101.0.0].
    - Conclusion: install magento/framework 101.0.0|install colinmollenhour/php-redis-session-abstract v1.3.4
    - Installation request for magento/framework (locked at 102.0.1) -> satisfiable by magento/framework[102.0.1].

**Comment by luckyraul** [comment]
https://github.com/mygento/module-metrika
